name: 'My Awesome list'
description: 'Generate awesome list from user starred repositories'
inputs:
  github-token:
    description: 'Github token'
    required: true
runs:
  using: 'node14'
  main: 'dist/index.js'
